{ config, pkgs, pkgs-unstable, lib, inputs, ... }:
{
  environment.systemPackages = (with pkgs; [
    vim 
    wget
    foot
    zsh
    zsh-completions
    zsh-autosuggestions
    pciutils
    discord
    lshw
    onlyoffice-bin
    nvtopPackages.full
    htop
    neofetch
    pywal
    wineWowPackages.staging
    winetricks
    wineWowPackages.waylandFull
    gparted
    auto-cpufreq
    brave
    heroic
    lutris
    libreoffice-qt6-fresh
    gimp
    protontricks
    waybar
    dunst
    libnotify
    rofi-wayland
    wofi
    pulseaudio
    pcmanfm
    networkmanagerapplet
    playerctl
    swww
    polkit
    lxqt.lxqt-policykit
    lemurs
    pavucontrol
    grim
    slurp
    killall
    obs-studio
    xorg.xhost
    hyprlock
    hypridle
    lxappearance
    chromium
    fzf
    wl-clipboard
    git
    xdg-desktop-portal-hyprland
    mangohud
    goverlay
    kdePackages.kdeconnect-kde
    mpv
    mpvScripts.mpris
    inputs.helix.packages."${pkgs.system}".helix
    btop
    sxiv
    zathura
    thunderbird
    vscodium
    neovim
    android-tools
    android-studio
    # davinci-resolve
    krita
    inkscape
    libsForQt5.kdenlive
    ncmpcpp
    mpc-cli
    mpd
    ags
    jdk
    python3Full
    # kicad
    fuzzel
    nwg-look
    shadps4
    eza
    nixd
    ntfs3g
    keepassxc
    # networkmanager
    libsixel
  ]) 
  
  ++ 
  
  (with pkgs-unstable; [
    matlab
    home-manager
  ]);
}
